# -*- coding: utf-8 -*-
"""Caminata_aleatoria.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d3sLyi5EzIPXPY45v7Pb_5OVyHgrJA31

# **Caminatas aleatorias 1D**
Vilchis García Karla Ivonne


---


Una caminata aleatoria 1D es un proceso estocástico donde una partícula se mueve sobre una línea, dando pasos de tamaño fijo hacia la izquierda o derecha con ciertas probabilidades en cada unidad de tiempo.


---



**Ejercicio:** Elaborar un código que implemente una camita aleatoria 1D, con probabilidad p de moverse a la derecha y probabilidad q de moverse a la izquierda, tal que p + q = 1.
"""

#importamos las paqueterías necesarias a utilizar
import random as rd
import numpy as np
import matplotlib.pyplot as plt

def caminata(n, p):
  pos=0
  camino=[pos]
  for _ in range(n):
    if rd.random()<p:
      pos+=1
    else:
      pos-=1
    camino.append(pos)
  return camino

n= 500  # Número de pasos
p=0.5 # probabilidad p de moverse a la derecha

# Ejecutar la caminata aleatoria usando la función 'caminata'
cam = caminata(n,p)

# Visualizar la caminata
plt.figure(figsize=(10, 5))
plt.plot(cam, color='purple')
plt.title(f'Caminata Aleatoria 1D')
plt.xlabel('Número de Pasos')
plt.ylabel('Posición')
plt.grid(True)
plt.show()

"""# **Análisis y Conclusiones**


---
¿Qué pasa cuando el valor de P aumenta?

"""

n= 500  # Número de pasos
p=0.7 # probabilidad p de moverse a la derecha

# Ejecutar la caminata aleatoria usando la función 'caminata'
cam1 = caminata(n,p)

# Visualizar la caminata
plt.figure(figsize=(10, 5))
plt.plot(cam1, color='purple')
plt.title(f'Caminata Aleatoria 1D')
plt.xlabel('Número de Pasos')
plt.ylabel('Posición')
plt.grid(True)
plt.show()

"""tiene una tendencia creciente, ya que la probabilidad de que se aumente a la derecha es mayor



---

¿Qué pasa cuando P disminuye?
"""

n= 500  # Número de pasos
p=0.2 # probabilidad p de moverse a la derecha

# Ejecutar la caminata aleatoria usando la función 'caminata'
cam2 = caminata(n,p)

# Visualizar la caminata
plt.figure(figsize=(10, 5))
plt.plot(cam2, color='purple')
plt.title(f'Caminata Aleatoria 1D')
plt.xlabel('Número de Pasos')
plt.ylabel('Posición')
plt.grid(True)
plt.show()

"""caso contrario a lo anterior, la tendencia de la caminata es decreciente, ya que se van agregando pasos a la izquierda.


---

¿Qué debe pasar con p para regresar al origen?
"""

n= 500  # Número de pasos
p=0.5 # probabilidad p de moverse a la derecha

# Ejecutar la caminata aleatoria usando la función 'caminata'
cam3 = caminata(n,p)

# Visualizar la caminata
plt.figure(figsize=(10, 5))
plt.plot(cam3, color='purple')
plt.title(f'Caminata Aleatoria 1D')
plt.xlabel('Número de Pasos')
plt.ylabel('Posición')
plt.grid(True)
plt.show()

"""Podemos notar que con un valor p de 0.5 hay más probabilidades de que regrese al origen la caminata aleatoria, sin embargo, puede pasar mucho para que esto suceda, ya que debería de aumentar y disminuir la misma cantidad de veces en ambos sentidos para regresar al origen.


---


¿Cuál es la posicion promedio de la caminata?

"""

pos_f=[]

for _ in range(1000):
  cams = caminata(1000,0.5)
  pos_f.append(cams[-1])
  plt.plot(cams)
plt.show()

media=np.mean(pos_f)

print('media de la posición final de 10 caminatas es', media)

"""Dando varioas valores para la cantidad de simulaciones que se hacen en el código, pude notar que cuando mayor era el número de las simulacoines, la media del último valor es cercana a 0, y cuando eran menos este valor variaba más, aunque claro, dando valores mayores nada asegura que la media sea cero.


---

¿Cuál es valor máximo y mínimo que puede tomar?
"""

n= 500  # Número de pasos
p=0.99 # probabilidad p de moverse a la derecha
m=500
pp=0.01

# Ejecutar la caminata aleatoria usando la función 'caminata'
cam4 = caminata(n,p)
cam5=caminata(m,pp)

# Visualizar la caminata
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))
ax1.plot(cam4, color='purple')
ax2.plot(cam5, color='blue')
ax1.set_title(f'Caminata Aleatoria 1D')
ax1.set_xlabel('Número de Pasos')
ax1.set_ylabel('Posición')
ax1.grid(True)
ax2.set_title(f'Caminata Aleatoria 1D')
ax2.set_xlabel('Número de Pasos')
ax2.set_ylabel('Posición')
ax2.grid(True)
plt.show()

"""mientras más cercano este el valor p de 1, el valor máximo será cercano  al número de pasos que tenga la caminata, caso contrario, mientras p sea cercano a 0, el valor mínimo será cercano al numero de pasos en negativo."""